### ISSUE TITLE
gcloud command not found

### ISSUE THREAD

**Issue by VishalUzumaki** [airavata-courses/ScrumLords#109]
![image](https://user-images.githubusercontent.com/22035884/77215541-8f723080-6ae2-11ea-8587-16365a398079.png)

Is it bash or do I need to install google cloud sdk?

**Comment by bobbyrathoree** [comment]
Yes, you need to install google cloud sdk.

**Comment by VishalUzumaki** [comment]
https://cloud.google.com/sdk/docs/downloads-interactive
I found this for windows.
