### ISSUE TITLE
Domain Needed

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/ScrumLords#114]
Hi Scrumlords, 
I'm trying to replicate Step 10, i.e. Create LetsEncrypt Prod Issuer
`kubectl create -f services/manager/deployment/production-issuer.yaml`

All errors in the earlier steps were resolved , however I am unable to proceed any further.
You also mentioned a private domain is required for replicating this, could you let me know how should I get one?

**Comment by bobbyrathoree** [comment]
Send me your subdomain hosts at my email and I'll add them as A records in my domain.

**Comment by ishita-kumar** [comment]
Sure will do
