### ISSUE TITLE
Static Dashboard Components

### ISSUE THREAD

**Issue by VishalUzumaki** [airavata-courses/ScrumLords#119]
Job status count static. Should be dynamic

**Comment by VishalUzumaki** [comment]
![image](https://user-images.githubusercontent.com/22035884/77218341-47f69f00-6af8-11ea-987f-1764cf6980eb.png)

**Comment by dhruv-y** [comment]
Thanks @VishalUzumaki I'll push the fix in a bit so you can verify the changes.
