### ISSUE TITLE
 Pubsub concurrency problem causing mismatched status

### ISSUE THREAD

**Issue by drishti2497** [airavata-courses/ScrumLords#37]
The services model_execution and post_processing are executed almost at the same time during the pipeline, and are sending the messages to api_manager and session_manager concurrently, causing the status to get updated in the wrong order.

**Comment by bobbyrathoree** [comment]
Great find @drishti2497 . We're actually working on fixing this problem.

**Comment by bobbyrathoree** [comment]
Fixed.
