### ISSUE TITLE
Dashboard can be accessed without authentication

### ISSUE THREAD

**Issue by aniruddhavpatil** [airavata-courses/ScrumLords#40]
`localhost:3000/dashboard` takes the user to the private route without going through login/register
Accessing a private link without having logged in should raise an error.

**Comment by dhruv-y** [comment]
Yup thanks for pointing that out, I'm on it.

**Comment by dhruv-y** [comment]
Hey Aniruddha, I have updated our protected routes to redirect you to the Login page when you try and access dashboards/session through the URL. 

If you want to check the changes, please refer to the commit in this thread.
