### ISSUE TITLE
Icon in the navbar redirects incorrectly.

### ISSUE THREAD

**Issue by JShivali** [airavata-courses/ScrumLords#41]
The icon in the navbar redirects incorrectly. On the landing page it redirects to the home page which works, but when clicked by a user that's logged in, it redirects him to a public route which is not desired.

**Comment by dhruv-y** [comment]
Thanks for pointing this point. I came across this issue while fixing a previous bug and was resolved in the latest commit (referenced above). Both my guest links and private links had the same redirection path set for the logo on the top left.

After the fix, the logo redirects the user to the dashboard when logged in and to the home page when logged out.
